[project]
name = "m18-protocol"
version = "0.1.0"
description = "Read Milwaukee M18 Protocol Data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyserial==3.5",
    "requests",
]
